highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://hodaesfahani.github.io
author: Fábio Madeira

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /cv/
title: Hoda Esfahani's Resume
name: Hoda Esfahani
email: hoda.esfahani@integrify.io
email_full: mailto:hoda.esfahani@integrify.io
github: hodaesfahani
linkedin: hoda-esfahani
tel: +358 41 725 75 98
tel_full: tel:+358 41 725 75 98
google_maps: 'https://goo.gl/maps/Vx3CqwB25K9u3VXm6'
address:
  street: Harjuviita 14 A 2
  postcode: '02110'
  city: Espoo
  country: Finland
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
